### PR TITLE
Fix for Issue #21 - Stepping through breakpoints sometime doesn't work

### PR DESCRIPTION
**Pull request by AutonomicCoder**
These two commits provide a fix for #21. Root cause was malformed `StackFrame.source`

### CODE REVIEW

**Comment by borgdylan** [comment]
This PR is not making a big difference with the case of Xamarin apps. The debugger is even failing to connect.

**Comment by AutonomicCoder** [comment]
@borgdylan Sorry, it looks like the Xamarin issue is separate.

**Comment by borgdylan** [comment]
I am rebuilding my Xamarin SDK to see if anything changes.

**Comment by borgdylan** [comment]
The issues were from changes done by Xamarin. Working around those and using your patch makes debugging work! Thank you!

**Comment by borgdylan** [comment]
Please merge this @weinand, fixes the issues I had. Is it working for you @buonan @tengxianbing ?

**Comment by buonan** [comment]
Works great for me!  I upgraded to VS Code 1.11.2, built issue#21 branch, installed the vsix and was able to debug/step through my mono project.

Thank you!

**Comment by weinand** [comment]
Thanks a lot for fixing #21.
I merged both commits but in general I suggest to submit features (e.g. logging to file) and fixes in separate PRs so that I can decide on a case by case basis what to merge and what not.

Please note that I'm already working on using the nuget package for the debug protocol (see https://github.com/Microsoft/vscode-mono-debug/issues/16). This will make some of the merged code obsolete. You can see a preview of that work in the aweinand/dap_nuget branch.

**Comment by AutonomicCoder** [comment]
@weinand - Happy to help 😄 . I completely understand regarding distinct PRs. Advice taken. 

Thanks for the merge while #16 is in the works. I'll take a look at `aweinand/dap_nuget` as well.

**Comment by borgdylan** [comment]
Good luck @weinand with the DAP work. This fix was a huge achievement. Here's to not having any regressions.

**Pull request merged**
