### PR TITLE
Remove dependency to SDB

### PR DESCRIPTION
**Pull request by t-h-e**
Neccessary packages have been added to packages.config
Some code from SDB is reused and was added to src/sdb
Removed SDB from project

### CODE REVIEW

**Comment by weinand** [comment]
@t-h-e Hi! Sorry for the late response...

What is the purpose/benefit of removing the dependency on SDB?

**Comment by weinand** [comment]
@t-h-e thanks for the PR!
On top of that I've removed lots of dead wood.

**Comment by t-h-e** [comment]
I should have linked the following issue: https://github.com/Microsoft/vscode-mono-debug/issues/12

**Comment by weinand** [comment]
@t-h-e oh, I see. I forgot about #12.
Could you try mono-debug on Windows and verify that it works for?
Then we could close #12.

**Comment by t-h-e** [comment]
works for me :)

**Comment by weinand** [comment]
great!

**Pull request merged**
